version: '3.7'

services:

  redis:
    image: redis:latest
    expose:
      - "6379"

  tcpunch:
    image: spcleth/tcpunch:latest
    # Needed to correctly handle signals
    tty: true
    init: true
    expose:
      - "10000"

  local_worker:
    image: praas/local_worker-dev
    # Needed to correctly handle signals
    tty: true
    init: true
    depends_on:
      - tcpunch
    expose:
      - "8080"
    volumes:
      - ./${DEV}:/dev-praas
    environment:
      - NUMPROCS=1

  control_plane:
    image: praas/control_plane-dev
    # Needed to correctly handle signals
    tty: true
    init: true
    depends_on:
      - redis
      - local_worker
      - tcpunch
    expose:
      - "8080"
    volumes:
      - ./${DEV}:/dev-praas
    environment:
      - REDIS_HOST=tcp://redis:6379
      - LOCAL_WORKER=local_worker:8080
      - IP_ADDRESS=control_plane

  haproxy:
    image: haproxy:latest
    depends_on:
      - control_plane
    volumes:
      - ./deployment/conf/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"


