version: '3.7'

services:

  redis:
    image: redis:latest
    expose:
      - "6379"

  control_plane:
    image: praas/control_plane-dev
    # Needed to correctly handle signals
    tty: true
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "8080:8080"
    expose:
      - "8080"
      - "5050"
    volumes:
      - ./${DEV}:/dev-praas
      - ./${SECRET_CERT}:/usr/local/etc/praas/server.pem:ro
      - ./${SECRET_KEY}:/usr/local/etc/praas/server.key:ro
    environment:
      - REDIS_HOST=tcp://redis:6379
      - LOCAL_WORKER=host.docker.internal:9000
      - IP_ADDRESS=host.docker.internal
      - HTTP_PORT=5050

  haproxy:
    image: haproxy:latest
    depends_on:
     - control_plane
    volumes:
      - ./deployment/conf/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./${SECRET_CERT}:/usr/local/etc/praas/server.pem:ro
      - ./${SECRET_KEY}:/usr/local/etc/praas/server.pem.key:ro
      - ./${CLIENT_CERT}:/usr/local/etc/praas/client.pem:ro
    ports:
      - "443:443"


